window.DESCRIPTIONS = {
  'doom-eternal': `La acción ahora se lleva a cabo en la Tierra, contra las fuerzas del Infierno que la han invadido. Se han revelado otros lugares, como la base humana en Phobos.

Varios años después de los eventos del Doom de 2016, la Tierra ha sido invadida por fuerzas demoníacas, eliminando al 60% de la población del planeta, bajo la ahora corrupta Union Aerospace Corporation (UAC). Lo que queda de la humanidad huyó de la Tierra o se unió como parte de la Coalición de Respuesta Blindada, más conocida como ARC por sus siglas en inglés, un movimiento de resistencia formado para detener la invasión, pero en la clandestinidad después de sufrir grandes pérdidas.

El Doom Slayer, que previamente había sido traicionado y teletransportado por el Dr. Samuel Hayden, regresa con una estación espacial controlada por la IA VEGA para sofocar la invasión demoníaca matando a los Sacerdotes del Infierno: Deags Nilox, Ranak y Grav.

Estos sacerdotes sirven a un ser angelical conocido como la Khan Maykr que busca sacrificar a la humanidad. El Slayer se teletransporta a un Los Ángeles destruido y mata a Deag Nilox, pero la Khan Maykr teletransporta a los dos sacerdotes restantes a lugares desconocidos, lo que obliga al protagonista a seguir buscando.

Después de recuperar un localizador celestial del mundo Centinela de Exultia, el Slayer viaja al Infierno para recuperar una fuente de energía de un Centinelas de la Noche caído conocido como el Traidor. Éste advierte al Slayer que ha llegado el momento de la humanidad antes de darle la fuente de poder y una daga especial. VEGA dirige al Slayer a una ciudadela en el Ártico donde Deag Ranak se ha refugiado, y el Slayer lo mata después de derrotar a su guardián Cazador infernal.

En respuesta, la Khan Maykr mueve a Deag Grav a un lugar oculto y acelera la invasión de la Tierra. Obligado a cambiar de táctica, el Slayer destruye el Supernido Sangriento en Europa central, donde comenzó la invasión. Sin pistas para encontrar al último Sacerdote del Infierno, VEGA sugiere encontrar al Dr. Hayden, quien conoce la ubicación de Deag Grav. El Slayer se dirige a un complejo ARC donde recupera el caparazón robótico de Hayden, así como el Crisol antes de enfrentarse a un Acechador, un Centinela demoníaco enviado para detenerlo.

Al cargar la mente de Hayden en la Fortaleza, se revela que Deag Grav se esconde en Sentinel Prime. El único portal a Sentinel Prime está ubicado en la antigua ciudad de Hebeth en el núcleo mismo de Marte, al que no hay acceso inmediato. El Slayer luego viaja a una instalación en Phobos donde usa la super arma BFG-10000 para producir un agujero en la corteza del planeta, que usa para llegar a Hebeth.

Después de llegar a Sentinel Prime, los flashbacks revelan que Slayer es Doomguy. Encontrado gravemente herido por los Centinelas, Doomguy fue llevado ante los Deag y se vio obligado a luchar en una arena de gladiadores. Impresionados por la crueldad de Doomguy en la batalla, los Deag lo indujeron a los Centinelas, mientras que el Khan Maykr investiga el conocimiento de Doomguy sobre los demonios.

En el presente, el Slayer encuentra a Deag Grav en la arena y derrota a un demonio masivo conocido como El Gladiador. A pesar de saber que es contra la ley Centinela asesinar a Deag Grav en terreno sagrado, el Asesino lo mata de todos modos y regresa a su Fortaleza.

A su regreso, la Fortaleza del Destino es bloqueada remotamente por la Khan Maykr para evitar más interferencias en sus planes. Ella revela sus intenciones de resucitar al súper depredador devorador de demonios, el Icono del Pecado, para consumir a la humanidad antes de que el Slayer sea atacado por los demonios. Sobreviviendo a la emboscada, éste utiliza la Energía Argent latente del Crisol demoníaco para reactivar la fortaleza y viaja a Argent D'Nur para recuperar su propio Crisol de su tiempo junto a los Centinelas.

Otros flashbacks revelan que durante la desafortunada batalla de Argent D'Nur, un Maykr pícaro conocido como Samur Maykr había imbuido al Doomguy con habilidades sobrehumanas, transformándolo en el Doom Slayer. Después de recuperar la empuñadura del Crisol, se revela que la Khan Maykr formó una alianza con el Infierno para producir energía Argent, que se crea a través del sacrificio masivo de almas humanas. A cambio de proporcionar mundos para que el Infierno los invada, los Maykrs reciben una parte de la energía Argent producida por el Infierno que permite que su propia dimensión, Urdak, sobreviva.

Samuel Hayden dirige al Slayer a través de la enorme ciudadela del Infierno, Nekravol, hasta que encuentra un portal que conduce a Urdak. Luego encuentra a la Khan Maykr y detiene la ceremonia del despertar usando la daga del Traidor para destruir el corazón del Icono. Libre del control de Maykr, el Icono del Pecado despierta de su estado latente y se teletransporta a la Tierra. Con la barrera dimensional destruida, los Demonios rompen su pacto con los Maykrs y proceden a invadir Urdak.

La Khan Maykr se enfrenta al Slayer, diciendo que Urdak debe destruir la Tierra para sobrevivir. Luchan y el Slayer mata a Khan Maykr antes de tomar un portal de regreso a la Tierra para confrontar al Icono del Pecado, aunque VEGA se queda atrás para garantizar que el portal permanezca abierto. Después de una intensa batalla a través del paisaje urbano, el Slayer mata al Icono del Pecado apuñalándolo en la cabeza con el Crisol, poniendo fin a la invasión de la Tierra por el Infierno.

Mientras el Slayer se aleja, el Rey Novik, líder de los Centinelas de la Noche, afirma que la lucha del Slayer es "eterna".`,

 'bayonetta-2': `En medio de una bulliciosa ciudad durante la temporada navideña, unos meses después de los eventos del primer juego,  Bayonetta  está haciendo algunas compras navideñas con Enzo a cuestas para llevar su gran cantidad de regalos, conociendo  a Jeanne  en el proceso. El viaje se interrumpe cuando los ángeles secuestran una actuación del equipo de aviones de acrobacias Platinum Stars, lo que obliga a Bayonetta a ponerse el traje y contraatacar. Finalmente, después de recibir un nuevo conjunto de armas de Rodin y unirse a Jeanne para derrotar a Belief , las cosas empeoran cuando el dragón demoníaco Gomorrah escapa de su portal después de ser invocado, ataca a Jeanne y hace que su alma sea arrastrada al Infierno  como parte del pacto de una bruja. A pesar de ser capaz de derrotar a Gomorrah, Bayonetta se queda con el cuerpo sin vida de su amiga.

En The Gates of Hell , Bayonetta dice que tiene la intención de rescatar a su amiga de Inferno , un acto que, según Rodin, no tiene probabilidades a su favor. No obstante, también explica cómo solo tiene una cantidad limitada de tiempo para salvar a Jeanne antes de que quede atrapada permanentemente en Inferno para siempre y dice que pondrá el cuerpo de Jeanne 'en hielo' para preservarlo. Le dicen que reunir el alma de Jeanne con su Umbran Watch , la fuente de la vida eterna de una Umbra Witch es la única forma de sacarla. Con esto en mente, Bayonetta atrapa a Enzo y lo hace llevarla a la montaña sagrada Fimbulventr . Se dice que la montaña es el único lugar en la Tierra que conecta el reino humano con Inferno y Paradiso . Enzo también menciona información de que el portal a Inferno, las literales Puertas del Infierno, está escondido allí y hasta ahora nunca ha sido descubierto por manos humanas.

Bayonetta llega a la ciudad en la base de la montaña, Noatun , para encontrar una manera de entrar en Inferno y rescatar a Jeanne de su destino. Ella conoce a un niño misterioso en  Purgatorio llamado Loki , quien expresa su sorpresa de que ella pueda verlo e interactuar con él. El niño es acosado por los ángeles que parecen querer evitar que llegue a la montaña. Sintiendo que sus objetivos para llegar a la montaña son los mismos, Loki llega a un acuerdo con Bayonetta para llevarlos a ambos a Fimbulventr mientras le explica que necesitará sus poderes para llevarla adentro.  Luka también llega a Noatun poco después de la llegada de Bayonetta, ofreciéndose a encontrar cualquier información adicional que pueda ayudarla a encontrar la puerta de entrada a Inferno. El viaje a la montaña sufre varios reveses de ángeles y demonios por igual y Bayonetta también se encuentra enfrentándose a  un Sabio Lumen  que parece decidido a matar a su guía.

Finalmente, Bayonetta y Loki llegan a las Puertas, solo para ser detenidos en seco por el Lumen Enmascarado y una proyección astral de  Loptr , un ser misterioso que parece conocer personalmente a Loki. Incapaz de evitar que el Sabio ataque a Loki, Bayonetta logra defenderse de Loptr hasta que él la derrota. Loptr la anima a "ver" con el poder del Ojo Izquierdo y le muestra una visión del pasado usando el  Recuerdo del Tiempo . Bayonetta se sorprende al ver que su padre no fue responsable de la Caza de Brujas y que intentó salvar a su madre de la muerte antes de que se lo llevaran. También ve una figura que se parece a Loki como el asesino. Mientras Loptr explica que es la verdad tal como realmente sucedió, el Lumen Enmascarado se prepara para derribar a Loki. El chico dispara sus cartas a las Puertas y le dice a Bayonetta que salte con él para escapar. Ella obedece y despierta para encontrarse en el Infierno. Al darse cuenta de que tiene poco tiempo para rescatar a Jeanne, se dirige a sus profundidades.

Bayonetta finalmente se encuentra con la demonio  Alraune  dentro de su palacio, descubriendo que ha tomado el alma de Jeanne para sí misma para volverse más poderosa. Al darse cuenta de que Bayonetta es una bruja de Umbra, así como del hecho de que tiene un pacto con Madama Butterfly, Alraune ataca salvajemente pero no es rival para los poderes de Bayonetta. Antes de que la bruja pueda asestar el golpe final, Rodin interviene y en su lugar sella a Alraune en una nueva arma . Bayonetta finalmente rescata el alma de Jeanne y la reúne con la guardia. Cuando su amiga no despierta inicialmente, Bayonetta vacila y le ruega que abra los ojos. Jeanne luego se despierta para alivio de Bayonetta y comienza a regresar a su cuerpo. Mientras se va, Jeanne advierte a Bayonetta que algo grande va a suceder en el mundo. Con su misión completada, Bayonetta vuelve su atención a Loki, a quien ve siendo atacado por el Lumen enmascarado. Interfiriendo una vez más en su venganza, Lumen Enmascarado se quita la máscara y revela ser un Balder más joven. Justo cuando había ganado la partida en una pelea, Loki reaparece repentinamente y libera una onda expansiva incontrolable de energía azul, arrastrando a Balder y Bayonetta hacia ella.

Bayonetta despierta y se da cuenta de que está 500 años en el pasado en Vigrid , durante la Cacería de Brujas . Para su sorpresa, se encuentra con Rosa viva y bien, y las dos brujas se unen para luchar contra la afluencia de ángeles decididos a destruir su santuario. Ayudando a su madre en combate con sus poderes y la Armadura Umbran, Bayonetta conoce a la versión más joven de Loptr, el doppelganger de Loki. Es aquí donde se da cuenta de que el eventual asesino de su madre estaría a manos de Loptr, no de Loki, y es lanzada en una explosión al Valle de la Media Luna. Balder, que ha sido transportado en el tiempo con ella, entra en el santuario para encontrar a Loptr que acaba de matar a Rosa. Bayonetta se da cuenta de que Loptr es por quien Balder debería buscar venganza y no Loki. Abre un portal que regresa al presente e implora a su padre que la siga, susurrando «Mamá...» en voz baja como último adiós a Rosa. En el presente, Loki ha logrado escapar del Infierno gracias a sus poderes y es encontrado por Luka. Le implora al periodista que lo lleve a la montaña, tras recordar quién es realmente y que debe detener el mal que es «lo único que queda». Loptr los apresa entonces a ambos.

En la actualidad, con la ayuda de Jeanne y un avión de combate, Bayonetta y Balder llegan a la cima de Fimbulventr y presencian cómo el anciano Loptr se apodera de Loki. Loptr explica que él y Loki fueron una vez dos mitades de la misma alma y que juntos eran originalmente el Dios del Caos, Aesir . La parte buena de Aesir, que eventualmente se convertiría en Loki, había decidido dividir su propia alma al dividir su poder en los Ojos del Mundo para mantener el equilibrio que tal división traería. Loki recibió el poder Soberano, el poder de controlar los Ojos como mejor le pareciera, mientras que Loptr, ahora revelado como la mitad malvada de Aesir, había recibido el poder Profético y la capacidad de supervisar la historia usando el Recuerdo del Tiempo. Sintiendo que necesitaba recuperar su poder, Loptr había decidido tomar los Ojos para su propio uso 500 años atrás en el pasado y recuperar el poder de Aesir para gobernar el reino. Sin embargo, Loki había escapado al futuro al darse cuenta de que Loptr necesitaría su poder y posteriormente había perdido la memoria en el proceso. Loptr tendría que esperar a encontrar a su 'media naranja' de nuevo para obtener el poder de tomar los Ojos y decidió traer al joven Balder al presente porque su yo mayor había muerto junto con el Ojo Derecho después de que Bayonetta derrotara a Jubileus . Balder rápidamente le arrebata el Ojo Derecho. Bayonetta lucha valientemente contra Loptr, pero finalmente es sometida y también le quitan el Ojo Izquierdo. Loptr, ahora habiendo obtenido el poder de su yo original y convertido en Aesir, se burla del libre albedrío humano y afirma que es el legítimo gobernante del reino humano del caos. Mientras Bayonetta y Balder luchan contra la deidad, Loki recuerda su poder oculto además de su capacidad para controlar los Ojos. Afirmando que el verdadero poder de Aesir reside en la "nada" y en la capacidad de borrar todo lo que desee del mundo, Loki usa ese poder para destruir los Ojos del presente y debilitar a Loptr para que vuelva a su estado original. Bayonetta y Balder realizan entonces una invocación conjunta y generan una fusión de Jubileus y la Reina Saba . El híbrido patea a Loptr, propulsando su cuerpo físico hacia el océano, donde una Gomorra invocada por Jeanne acecha para engullirlo por completo.

Mientras el alma de Loptr intenta escapar al reino espiritual para renacer en otro lugar y repetir su plan, Balder interviene y lo absorbe a pesar de las advertencias de Loki de que Loptr lo corromperá para siempre si permanece dentro. Balder se conforma con el sacrificio para demostrar la fuerza del libre albedrío humano y revela que siempre supo que Bayonetta era Cereza. Le hace prometer que será quien lo detenga si alguna vez se desvía de su camino gracias a la influencia de Loptr, y ella accede a su petición de volver a llamarlo "Papá". Llora tras él cuando es transportado de vuelta a su tiempo, dándose cuenta finalmente de que no tenía la culpa de sus planes con Jubileus. Loki, tras haber cumplido su propósito y haber restaurado el equilibrio del mundo con la destrucción de ambos Ojos, comienza a desvanecerse. Bayonetta le pregunta si lo volverá a ver, y el chico responde que quizás lo hagan en el futuro, cuando renazca tras un descanso. Él comenta que ella todavía no le parece una Cereza antes de desaparecer en una neblina azul.

Pasaron varios días desde los sucesos en Fimbulventr, y tanto Bayonetta como Jeanne disfrutaban de otra salida de compras para aprovechar las rebajas posnavideñas. Mientras presenciaban cómo Luka ayudaba a Rodin a anunciar su bar, una mujer y un bebé en un cochecito pasaban justo cuando una de las tarjetas de Loki revoloteaba, insinuando que su regreso llegaría antes de lo que Bayonetta creía. Bayonetta recordó entonces que se había olvidado por completo de Enzo en Noatun. Enzo regresaba en un aterrizaje forzoso calle abajo en el avión en el que lo habían dejado, perseguido por ángeles. A pesar de su molestia por arruinar un segundo vestido en un mes, Bayonetta se subía a las alas del avión con Jeanne para luchar contra sus agresores como siempre lo habían hecho.`
};